[package]
name = "lsp_proxy"
version = "0.1.0"
authors = ["Ayomide Bamidele <ayoeze@hotmail.com>"]
edition = "2018"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "app"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
structopt = "0.3.17"
clap = "2.33.3"
actix-files = "0.3.0"
mime = "0.3.16"

[dev-dependencies]
actix-rt = "1"
reqwest = "0.10.8"
tokio = "0.2.22"
